version: "3.8"
services:
    api:
        image: hseeberger/scala-sbt:8u282_1.5.4_2.11.12
        volumes: 
            - ..:/root
        working_dir: /root
        ports: 
            - "9000:9000"
        depends_on:
            - mysql
            
    mysql:
        build: "./mysql"
        volumes:
            - ./mysql/sql:/docker-entrypoint-initdb.d
        ports:
            - "13306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: playsample
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            